apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litmus-chaos-monitor
rules:
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosresults"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: litmus-chaos-monitor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus-chaos-monitor
subjects:
- kind: ServiceAccount
  name: litmus
  namespace: litmus
